### ISSUE TITLE
Elden Ring Example?

### ISSUE THREAD

**Issue by michael-mclawhorn** [malywut/gpt_examples#1]
I just saw a presentation citing this repo as the source for a more complex example using three stages and outputting to a Jupyter notebook.  I don't see any relevant branches with that code here.  Is a push with that forthcoming?

**Comment by malywut** [comment]
Hi, the code is here : https://github.com/malywut/gpt_examples/tree/main/02_QuestionAnsweringOnPDF
The Elden Ring pdf is not included, but you can use any pdf.

**Comment by michael-mclawhorn** [comment]
thanks!
