### ISSUE TITLE
Voice Assistant - Loop Error

### ISSUE THREAD

**Issue by jluvizon** [malywut/gpt_examples#11]
Hello,

It seems that the voice assistant is not working properly. I ran it by recording "Hi" and it went in a loop as you can see in the image below:

![image](https://github.com/malywut/gpt_examples/assets/709138/2f752a57-db22-416a-b16c-62056ae9cb03)

**Comment by malywut** [comment]
Hi! It seems that the recent updates of the model have broken this project.
I will work on the prompt to fix it.

Meanwhile, you can try with GPT-4 or older snapshots of gpt-3.5 turbo, and see if it helps.

**Comment by godfreynolan** [comment]
It looks like you're using the old way of calling whisper.  
You shouldn't need to import whisper, it's all in import openai now and you then use the following type of call
    transcription = openai.audio.transcriptions.create(
        model="whisper-1",
        file=media_file,
    )

**Comment by malywut** [comment]
@godfreynolan whisper can still be used locally and for free, and we used it this way to show different possibilities. The OpenAI API provides remotely the latest whisper model, but at a cost.

**Comment by malywut** [comment]
This issue has been fixed with the book's second edition.
