### ISSUE TITLE
How to run Chap3_03_QuestionAnsweringOnPDF example?

### ISSUE THREAD

**Issue by yurisalesc** [malywut/gpt_examples#13]
Reading the book and writing the code from the example, It's not clear to me how to run the project beyond the docker-compose up. What should I do to make it work?

Tried to run the run.py with `docker exec -it openai-book_vector-db_1 python run.py ` but the python is not found.

**Comment by malywut** [comment]
The Docker container is only to set-up Redis. It exposes the standard Redis
port.
Once it is running, we can access it locally. The command
    python run.py
should be executed locally.
Let me know if you have any other issues!
