### ISSUE TITLE
Chap3_03_QuestionAnsweringOnPDF

### ISSUE THREAD

**Issue by amscosta** [malywut/gpt_examples#4]
Hello
In the book , you said 
"We start by using Docker to launch a Redis instance. You will find a basic redis.conf
file and a docker-compose.yml file as an example in the GitHub repository."
I am afraid the redis.conf is not in the github repository.
Also, Could you write some command lines about the .yml usage (and the redis.conf)?
Surely, it will improve  the reach of your book.
Best regards.

**Comment by malywut** [comment]
Hello, thanks for raising this issue!
The redis.conf file is not used in the latest version. I will fix this in the book.

However, if you want to change the redis configuration, it would be possible by editing the docker-compose.yml file, by adding the file in the volumes section:

```
volumes:
      - vector-db:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
```

And creating a redis configuration file at ./redis/redis.conf.

The docker-compose.yml file is read by the docker command : 
`docker compose up`
(or `docker-compose up`)

You can find more information here: https://docs.docker.com/compose/reference/

Thank you for raising this, I will make some changes to the book to make it more clear in the next version.
Please let me know if you have other questions.
