### ISSUE TITLE
Chap3_03_QuestionAnsweringOnPDF - docker-compose file

### ISSUE THREAD

**Issue by ClimberBear** [malywut/gpt_examples#6]
Hi

As you have removed the config file, the current version does not match the data directory.

In the entrypoint.sh the data dir is configured as:

`REDIS_DATA_DIR=/data`

but the docker compose mount as volume

`      - vector-db:/var/lib/redis`

So, I cannot save the vector database among sessions.

For the moment, I have corrected the vector-db as

```
    environment:
      - REDISEARCH_ARGS=CONCURRENT_WRITE_MODE
      - REDIS_DATA_DIR=/data
    volumes:
      - vector-db:/data
```

**Comment by malywut** [comment]
Hi, thanks for raising this issue. Indeed the default data dir is /data.
I'll correct this as you suggested.
