### ISSUE TITLE
Voice Assistant error

### ISSUE THREAD

**Issue by gnolanltu** [malywut/gpt_examples#9]
Getting the following error when running the Gradio/Whisper example from the command line in Windows 11

![image](https://github.com/malywut/gpt_examples/assets/21340349/b9260981-7f06-4242-beef-bedd92591516)

**Comment by malywut** [comment]
Hi, can you tell me what version of radio are you using? 
`pip show gradio`

**Comment by gnolanltu** [comment]
Name: gradio
Version: 4.21.0

**Comment by malywut** [comment]
Hi, 
I have updated all the libraries to more recent versions.
`source` parameter has been changed to `sources` in the latest Gradio library.

You should not have any error now. Do not hesitate to open other issues if needed.

A warning: I have found that this project works less well with the latest gpt-3.5-turbo model. I will work on the prompts to fix that.
